# Site settings
baseurl = "https://example.org/"
themesDir = "../.."
languageCode = "en-us"
title = "Oblate"
theme = "hugo-oblate-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[taxonomies]
  category = "categories"

[params]
  name = "John Doe"
	description = "Describe your website"
  enableRSS = true
  subscribe = ""
  # you can use emoji or image params for displaying icons near the title 
  emoji = "ğŸ‘¨ğŸ»â€ğŸ’»"
  # image = "/images/floppy.png"
  customCSS = ['css/main.css']
  emojicom = ""
  # default titles
  articles = ""
  latestPosts = ""
  projects = ""
  copyright = false

# Add additional social link entries underneath
[social]
		linkedin = "https://www.linkedin.com/in/"
    github   = "https://www.github.com/zapatran"
		instagram = "https://www.instagram.com/"