# Site settings
baseurl = "https://example.org/"
themesDir = "../.."
languageCode = "en-us"
title = "Oblate"
theme = "hugo-oblate-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[taxonomies]
  category = "categories"

[params]
  # for meta porpouses
  name = "John Doe"
	description = "Describe your website"
  enableRSS = true
  subscribe = ""
  # you can use emoji or image params for displaying icons near the title 
  emoji = "ğŸ‘¨ğŸ»â€ğŸ’»"
  # image = "/images/floppy.png"
  customCSS = ['css/main.css']
  emojicom = ""
  copyright = false

# Add additional social link entries underneath
[social]
		linkedin = "https://www.linkedin.com/in/"
    github   = "https://www.github.com/zapatran"
		instagram = "https://www.instagram.com/"

[languages]
  [languages.en]
    weight = 1
    languageName = "ğŸ‡ºğŸ‡¸"
    projects = "Projects"
    contentDir = "content/english"
    articles = "Articles"
    latestPosts = "Lastest posts"
  [languages.es]
    weight = 2
    languageName = "ğŸ‡ªğŸ‡¸"
    projects = "Proyectos"
    contentDir = "content/spanish"
    articles = "ArtÃ­culos"
    latestPosts = "Ãšltimas entradas"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS"]
